### ISSUE TITLE
Can we make it available in Nerd Font repo?

### ISSUE THREAD

**Issue by cpea2506** [shaunsingh/SFMono-Nerd-Font-Ligaturized#13]
Currently, there is a new version from [nerd-fonts](https://www.nerdfonts.com/font-downloads) that has new glyph for `TOML` icon. But I think it would take a long time for you and other to realize. I think this is better if we can get it directly from `nerd-fonts`. So it can receive update faster and more regularly.

Also, we can make use of some tools like: [getnf](https://github.com/ronniedroid/getnf)

**Comment by shaunsingh** [comment]
Technically the original license for the font disallows for modification and resharing, according to them the font is for "third-party developers only for the design and development of applications for Apple's platforms"

You're welcome to PR it to nerd fonts if you'd like of course, but I imagine they'd reject it on the basis of licensing. Also keep in mind this repo uses a few glyphs from fira for the ligatures, not sure how the licensing for that works

**Comment by cpea2506** [comment]
Ah! Thank for your response, I can see. I will take a look at license and see if I can do anything.
