### ISSUE TITLE
Installation: Is it possible to install the font on windows machines?

### ISSUE THREAD

**Issue by 0xlebogang** [shaunsingh/SFMono-Nerd-Font-Ligaturized#15]
The font and all the provided installation methods are Unix based.  Will it be possible to install the font on Windows machines or is everything made to only accept the architecture of Unix based machines?

**Comment by Vortigern-The-Grey** [comment]
Simple! Just download the fonts you want as .otf files and open them to install!

**Comment by 0xlebogang** [comment]
> Simple! Just download the fonts you want as .otf files and open them to install!

Thank you Vortigern
