### ISSUE TITLE
Q: How to install?

### ISSUE THREAD

**Issue by corneliusroemer** [shaunsingh/SFMono-Nerd-Font-Ligaturized#4]
How do you install the fonts? Clone the repo and then? Copy the fonts?

**Comment by shaunsingh** [comment]
On macOS: Clone the repo, highlight all the `.otf` files, double click and they should preview/install through font book

On linux, you can copy them over to ~/.local/share/fonts

**Comment by corneliusroemer** [comment]
Excellent - thanks! That worked.

Maybe add that to the README for noobs like me?
